module.exports = {
    CONFIG: {
        CONDITION: {
            EXPIRED: 20,
            NAP: 0,
            SPEND: 0
        }
    },
    CURRENCY: "VNĐ",
    SUCCESS: "success",
    SUCCESS_PROCEDURE_RESPONSE_CODE: 1,
    UPDATE_SUCCESS_RESPONSE_TEXT: "Update successful",
    INSERT_SUCCESS_RESPONSE_TEXT: "Successfully added new",
    UPDATE_FAIL_RESPONSE_TEXT: "Update failed. Please try again later!",
    ERROR_PAGE: {
        NOT_FOUND: "This page does not exist",
        INTERNAL_SERVER_ERROR: "Internal Server Error",
        BAD_REQUEST: "Bad Request",
        UNAUTHORIZED: "Unauthorized",
        FORBIDDEN: "Forbidden",
        NOT_FOUND: "Not Found",
        MAINTERNANCE: "The system is under maintenance, please try again later!",
        WEBSITE_OPERATIONS_NORMAL_WOOD: "Website operations normal wood!",
    },
    ERROR_FORM: {
        MISSING_FIELD: "Input field value is missing",
        MISSING_PAGE: "Missing page value",
        MISSING_NICKNAME: "Please enter your characters name"
    },
    ERROR_AUTH: {
        TOKEN_INVALID: "Access Token Invalid",
        NO_ACCESS: "Not authorized to access this resource",
        LOGIN_FAIL: "Incorrect account or password!",
        OTP_CODE_INVALID: "Invalid OTP Code",
        NOT_FOUND_REFERER_CODE: "Affilate Code Not Found",
        PASSWORD_INVALID: "Incorrect password!",
        RequestPasswordReset: "Request a password reset",
    },
    ERROR_AGENT: {
        AGENT_NOT_FOUND: "Agent does not exist!!!",
        AGENT_CANT_CREATE: "Unable to create agent!",
        AGENT_USERNAME_SAME_AS_ORTHER_AGENT: "Username is already the same as someone else's!",
        AGENT_USERNAME_MUST_OTHER_PASSWORD: "The account cannot match the password!!",
        AGENT_NAME_LESS_THAN: "Dealer name (3-32 characters).",
        AGENT_USERNAME_LESS_THAN: "Dealer name (3-32 characters).",
        AGENT_NAME_MUST_BE_STRING_OR_NUMBER: "Dealer name only consists of letters and numbers!!",
        AGENT_USERNAME_MUST_BE_STRING_OR_NUMBER: "Dealer username only consists of letters and numbers!!",
        AGENT_REFERER_CODE_LESS_THAN: "Referral code (3-32 characters).",
        AGENT_REFERER_CODE_MUST_BE_STRING_OR_NUMBER: "Referral code only consists of letters and numbers !!",
        AGENT_REFERER_CODE_MUST_BE_ORTHER_PLAYER_NICKNAME: "Referral code must be different from the player name!"
    },
    ERROR_AUTH_MESSAGE: {
        AccessDenied: "This resource is not allowed",
        InvalidName: "Invalid first and last name",
        InvalidUsername: "Invalid account name",
        InvalidField: "Invalid account name",
        InvalidEmail: "Invalid email",
        InvalidPasswordShort: "Password is too short",
        InvalidPasswordNotMatch: "2 passwords are not the same",
        UsernameExists: "This username is already registered to another user",
        EmailExists: "This email is already registered with another user",
        NotVerify: "Your account is not verified",
        InvalidCode: "Invalid verification code",
        AccountHasVerify: "This account has been verified",
        InvalidReferer: "Người giới thiệu không hợp lệ",
        MissingFieldList: "Vui lòng nhập đầy đủ thông tin",
        ErrorParams: "Thông số lỗi",
        InvalidRefcode: "Mã đại lý không hợp lệ!",
        AgencyNotFound: "Không tìm thấy đại lý với mã",
    },
    ERROR_CODES: {
        InvalidLoginCredentials: "Thất bại",
        InvalidOrExpiredToken: "Token không hợp lệ hoặc đã hết hạn",
        AccessDenied: "Từ chối truy cập",
        NeedActive: "Tài khoản chưa được cấp quyền truy cập",
        NeedVerify: "Tài khoản chưa được xác minh",
        SomeErrorsOccurredPleaseTryAgain: "An error occurred, please try again",
        NoPermissionToAccessThisResource: "Không có quyền truy cập tài nguyên này",
        AccountBlocked: "Tài khoản đã bị khóa",
        AccountNotFound: "Account not found",
        InvalidVerifyCode: "Mã xác minh không hợp lệ",
        PhoneNotFound: "No account found with this phone number",
    },
    ERROR_MESSAGES: {
        MissingFieldList: "Please enter full information",
        ErrorTaskName: "Invalid name",
        ErrorNameLength: "The length of the first and last name must be greater than 8 and less than 50 characters",
        ErrorUsernameLength: "Username length must be greater than 5 and less than 20 characters",
        ErrorTaskUrl: "Url không hợp lệ",
        ErrorTaskLoop: "Thời gian lặp không hợp lệ",
        ErrorService: "Service không hợp lệ",
        ErrorTimeUsage: "Thời gian sử dụng không hợp lệ",
        ErrorServiceNotFound: "Service không tồn tại",
        ErrorTasknameTextLength: "The length of the name must be greater than 3 and less than 30 characters",
        ErrorTaskLoopZeroValue: "Thời gian lặp phải có giá trị lớn hơn 0",
        ErrorServiceZeroValue: "Vui lòng chọn Service",
        ErrorTimeUsageZeroValue: "Thời gian sử dụng phải có giá trị lớn hơn 0",
        ErrorMissingTaskID: "Vui lòng nhập task ID",
        ErrorTaskNotFound: "Không tìm thấy Task",
        ErrorOldPassword: "Mật khẩu cũ không đúng",
        ErrorHasNotExpiredYet: "Yêu cầu trước đó chưa hết hiệu lực! Vui lòng thử lại sau khi hiệu lực kết thúc!",
    },
    ERROR_CHECKOUT_MESSAGES: {
        InsufficientBalance: "Tài khoản không đủ số dư",
        ErrorTaskName: "Tên không hợp lệ",
        ErrorTaskUrl: "Url không hợp lệ",
        ErrorTaskLoop: "Thời gian lặp không hợp lệ",
        ErrorService: "Service không hợp lệ",
        ErrorTimeUsage: "Thời gian sử dụng không hợp lệ",
        ErrorServiceNotFound: "Service không tồn tại",
        ErrorTasknameTextLength: "Độ dài của tên phải lớn hơn 3 và nhỏ hơn 14 ký tự",
        ErrorTaskLoopZeroValue: "Thời gian lặp phải có giá trị lớn hơn 0",
        ErrorServiceZeroValue: "Giá trị service phục vụ phải có giá trị lớn hơn 0",
        ErrorTimeUsageZeroValue: "Thời gian sử dụng phải có giá trị lớn hơn 0",
    },
    INFORMATION_ENUMS: {
        SITENAME: "NODE CRON VIP PRO",
        PRICEONETASK: 500,
    },
    ERROR_SERVER: {
        WRONG: "Có lỗi xảy ra, vui lòng thử lại!"
    },
    ERROR_QUERY: {
        USER_NOT_FOUND: "user not found",
    },
    ERROR_CUSTOM: {
        PASSWORD_LESS_THAN: "Mật khẩu quá ngắn!!!"
    },
    PAYMENT_API: {
        ERROR_AUTH: {
            MISSING_API_KEY: "Missing API Key!",
            MISSING_API_SECRET: "Missing API Secret!",
            MISSING_ACCESS_TOKEN: "Missing Access Token!",
            MISSING_REFRESH_TOKEN: "Missing Refresh Token!",
            MISSING_CODE: "Missing Code!",
            MISSING_TOKEN: "Missing Token!",
            API_KEY_INVALID: "Api Key Invalid",
            API_SCRET_INVALID: "Api Secret Invalid",
            NO_ACCESS: "Not authorized to access this resource",
            ACCOUNT_IS_PENDING: "Your account is temporarily unavailable, contact support for more detail.",
            ACCOUNT_IS_BLOCKED: "Your account is temporarily locked, contact support for more details.",
            LOGIN_FAIL: "Incorrect account or password!",
            NOT_FOUND_REFERER_CODE: "Affilate Code Not Found",
            PASSWORD_INVALID: "Incorrect password!",
            RequestPasswordReset: "Request a password reset",
        },
        ERROR_DATA: {
            NO_RESOURCES_ADDED: "Your account has not been assigned resources to use this feature!",
            THIS_BANKCODE_IS_NOT_SUPPORT: "This bank code is not supported.",
            THIS_BANKCODE_IS_NOT_HAVE_RESOURCES: "This bank code is not unassigned resource",
            THIS_BANKCODE_NOT_ASSIGN_FOR_ACCOUNT: "Your account has not been assigned resources for this bank code.",
            THIS_BANKCODE_IS_NOT_AVAILABLE: "This bank code is not available",
            THIS_BANKCODE_IS_NOT_ACTIVE: "This bank code is not active",
            THIS_BANKCODE_IS_NOT_VERIFIED: "This bank code is not verified",
            THIS_BANKCODE_IS_NOT_AVAILABLE_FOR_USER: "This bank code is not available for user",
            THIS_TRANSACTION_IS_EXISTED: "Transaction is already exists.",
            THIS_TRANSACTION_IS_NOT_EXISTED: "Transaction is not exists.",
            THIS_TRANSACTION_IS_CANCEL_BEFORE: "This transaction has been canceled before.",
            THIS_TRANSACTION_IS_COMPLETE_OR_CANNOT_CANCEL: "This transaction has been completed or cannot be canceled!",
            ERROR_CREATE_CONTENT_TRANSACTION: "Error create transaction content.",
            ERROR_CREATE_TRANSACTION: "Error create transaction.",
            ERROR_WALLET_BALANCE_NOT_ENOUGHT: "Your wallet balance is not enough."
        },
        ERROR_PARAMETER: {
            MISSING_PARAMETER: "Missing parameter.",
            INVALID_PARAMETER: "Invalid parameter",
            INVALID_PARAMETER_VALUE: "Invalid parameter value",
            INVALID_PARAMETER_TYPE: "Invalid parameter type",
            INVALID_PARAMETER_LENGTH: "Invalid parameter length",
            REQUEST_ID_INVALID: "request id invalid",
            BANK_ACCOUNT_INVALID: "bank account invalid",
            BANK_NAME_INVALID: "bank name invalid",
            SIGNATURE_INVALID: "signature invalid",
        },
        ERROR_CONDITION: {
            MINIUM_AMOUNT_DEPOSIT: "Minimum amount is ",
            MIXIMUM_AMOUNT_DEPOSIT: "Maximum amount is ",
            MINIUM_AMOUNT_WITHDRAW: "Minimum amount is ",
            MIXIMUM_AMOUNT_WITHDRAW: "Maximum amount is ",
            INVALID_CONDITION_VALUE: "Invalid condition value",
            INVALID_CONDITION_TYPE: "Invalid condition type",
            INVALID_CONDITION_LENGTH: "Invalid condition length",
        },
        ERROR_MESSAGE: {
            TRANSACTION_IS_PROGRESS: "The transaction is in progress."
        },
        ERROR_SYSTEM: {
            NOT_FOUND_DATA: "This data is not found!"
        }
    }
};